In [4]:
import numpy as np
n = np.array([(1,2,3),(3,4,5)])
print(n)

[[1 2 3]
 [3 4 5]]


In [5]:
import numpy as np
n = np.array([(1,2,3),(3,4,5)])
print(n.ndim)

2


In [7]:
import numpy as np
a = np.array([1,2,3])
print(a.itemsize)

8


In [8]:
import numpy as np
a = np.array([1,2,3])
print(a.dtype)

int64


In [9]:
import numpy as np
a = np.array([(1,2,3),(3,4,5)])
print(a.size)

6


In [10]:
import numpy as np
a = np.array([(1,2,3),(3,4,5)])
print(a.shape)

(2, 3)


In [11]:
import numpy as np
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a.reshape(4,2))

[[1 2]
 [3 4]
 [3 4]
 [5 6]]


In [13]:
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
print(a[0,2])

3


In [14]:
import numpy as np
a = np.array([1,3,5,4,7,8,2])
print(a.min())

1


In [15]:
import numpy as np
a = np.array([1,3,5,4,7,8,2])
print(a.max())

8


In [16]:
import numpy as np
a = np.array([1,3,5,4,7,8,2])
print(a.sum())

30


In [18]:
import numpy as np
a = np.array([(1,3,4),(3,4,5)])
print(a.sum(axis = 0))

[4 7 9]


In [20]:
import numpy as np
a = np.array([(1,3,4),(3,4,5)])
print(np.sqrt(a))

[[1.         1.73205081 2.        ]
 [1.73205081 2.         2.23606798]]


In [21]:
import numpy as np
a = np.array([(1,3,4),(3,4,5)])
print(np.std(a))

1.2472191289246473


In [22]:
import numpy as np
a = np.array([(1,2,3),(3,4,5)])
b = np.array([(5,7,3),(8,7,3)])
print(a+b)

[[ 6  9  6]
 [11 11  8]]


In [26]:
import numpy as np
a = np.array([(1,2,3),(3,4,5)])
b = np.array([(5,7,3),(8,7,3)])
print(a*b)

[[ 5 14  9]
 [24 28 15]]


In [28]:
import numpy as np
a = np.array([1,2,3])
print(np.log(a))

[0.         0.69314718 1.09861229]
